### ISSUE TITLE
Suggestion - no need to specify font-weight: bold on h1 and h2

### ISSUE THREAD

**Issue by jzhu01** [laurenbertca/prj-rev-bwfs-dasmoto#3]
Seen here: https://github.com/laurenbertca/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/index.css#L17

Since these headings are already bolded by default, there's no need to specify this here.

**Comment by laurenbertca** [comment]
Oh, good to know. Thanks!
