### ISSUE TITLE
Suggestion - instead of using strong tags, use spans

### ISSUE THREAD

**Issue by jzhu01** [laurenbertca/prj-rev-bwfs-dasmoto#4]
Seen here: https://github.com/laurenbertca/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L14

Since strong is a stylistic tag (i.e. it changes the style of the text) that breaks our programming paradigm of HTML containing content only and CSS containing styling. I recommend using spans instead and styling the spans to be bold in your css.

**Comment by laurenbertca** [comment]
Thanks, I totally forgot about spans this makes a ton of sense! I knew it wasn't the right way but couldn't figure out how to add to a limited
